### ISSUE TITLE
where is "antlr4py3"?

### ISSUE THREAD

**Issue by taodongl** [jszheng/py3antlr4book#1]
I know

**Comment by jtmoon79** [comment]
So where is it?

**Comment by SpencerPark** [comment]
In case some future visitor comes across this, it's created like an alias in [bin/antlr4env.bat](https://github.com/jszheng/py3antlr4book/blob/5490e20f6b66f04e3a5db868c5876b609c5e66d6/bin/antlr4env.bat) after you run that script like it mentions in the instructions for windows.
